version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      weekly-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
