[package]
name = "kondo-ui"
version = "0.1.0"
authors = ["Trent Billington <trent.h.billington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.5.0"

[dependencies.kondo-lib]
path = "../kondo-lib"
version = "*"

[profile.release]
incremental = false
lto = true
codegen-units = 1
opt-level = "z"
